trigger:
- main  # Replace 'main' with the branch name you want to trigger on

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo 'This is a placeholder build step.'
      displayName: 'Build Step'
