trigger:
- none

pr:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: |
    # Log in to Azure using a service connection or a service principal
    az login --service-principal -u ee36e6a6-05c7-46cc-8cf8-851c13e4ea8a -p QxJ8Q~FOQ.w4X5Y5tj6EAmPZ60q6D6jxbPEJzbru --tenant 36a13575-d209-4c82-a998-b67a504cb7cc

    # Set the Azure subscription
    az account set --subscription 6373a757-98f6-48e6-acab-41a30e2627e1

    # Define ACR and image details
    acrName=sermadregistry
    imageName=myimage
    imageTag=latest
    imageSourceDir=SermadMehdi/AzureDevops/Dockerfile

    # Build the Docker image
    az acr build --registry $acrName --image $imageName:$imageTag $imageSourceDir

    # Define container instance parameters
    resourceGroupName=harpoon
    containerName=pipelinetest
    cpu=1
    memory=1.5
    location=eastus

    # Create the container instance
    az container create --resource-group $resourceGroupName --name $containerName --image $acrName.azurecr.io/$imageName:$imageTag --cpu $cpu --memory $memory --location $location

  displayName: 'Build Docker Image and Create Container Instance'
