trigger:
- master  # Define the branch to trigger the pipeline

pool:
  vmImage: 'windows-latest'  # Use an appropriate agent based on your project requirements

steps:
- script: |
    # Define your build steps here
    # For example, let's assume you have a Node.js application
    npm install
    npm run build
  displayName: 'Build Application'
  workingDirectory: $(Build.SourcesDirectory)  # Set the working directory as per your project structure

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'  # Define the path to your built artifacts
    ArtifactName: 'webapp'  # Specify a name for the artifact
