trigger:
  branches:
    include:
      - 'dbt'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Logging in to Azure Container Registry"
    az acr login --name sermadregistry --username sermadregistry --password RlSzeKGcLJsv16ATAd1gqXvuqx7Py8vMeXGTXUqb+f+ACRAs/ohh

    echo "Building DBT core image"
    docker build -t sermadregistry.azurecr.io/dbt-core:latest .

    echo "Pushing DBT core image to ACR"
    docker push sermadregistry.azurecr.io/dbt-core:latest
  displayName: 'Build and Push DBT Core Image'
  workingDirectory: $(Build.SourcesDirectory)

- script: |
    echo "Logging in to Azure CLI using the service connection"
    az login --service-principal -u $(serviceConnectionUsername) -p $(serviceConnectionPassword) --tenant $(serviceConnectionTenant)

    echo "Creating Azure Container Instance for DBT Core"
    az container create --resource-group harpoon \
                        --name dbt-core-container \
                        --image sermadregistry.azurecr.io/dbt-core:latest \
                        --cpu 1 --memory 1.5 \
                        --restart-policy OnFailure
  displayName: 'Create DBT Core Container'
  env:
    serviceConnectionUsername: $(AllConnection.servicePrincipalId)
    serviceConnectionPassword: $(AllConnection.servicePrincipalKey)
    serviceConnectionTenant: $(AllConnection.servicePrincipalTenantId)
