trigger:
  branches:
    include:
      - dbt

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Logging in to Azure Container Registry"
    az acr login --name sermadregistry --username sermadregistry --password RlSzeKGcLJsv16ATAd1gqXvuqx7Py8vMeXGTXUqb+f+ACRAs/ohh

    echo "Building DBT core image"
    docker build -t sermadregistry.azurecr.io/dbt-core:latest .

    echo "Pushing DBT core image to ACR"
    docker push sermadregistry.azurecr.io/dbt-core:latest
  displayName: 'Build and Push DBT Core Image'
  workingDirectory: $(Build.SourcesDirectory)  # Set the working directory to the root of the source directory